postgresql: &postgresql
  adapter: postgresql
  host: localhost
  min_messages: ERROR
  username: 
  password: 
  pool: 5
  timeout: 5000

development:
  <<: *postgresql
  database: infraction_development

test:
  <<: *postgresql
  database: infraction_test

production:
  <<: *postgresql
  database: infraction_production
